import { Jugador} from "@/interfaces";

interface SeedData {
    jugadores: Jugador[],
}

export const listaJugadores :SeedData ={
jugadores:
[
    {
     "codigo": 20075,
     "nombre": "Albis Pena",
     "vicepresidencia": "TIS",
     "area": "CORE NETWORK & PLATFORMS",
     "confirmacion": "Si",
     "posicion": "F",
     "estatura": "5-11",
     "equipo": "Draft",
     "ronda": "1",
     "pick": "0"
    },
    {
     "codigo": 24509,
     "nombre": "Alex Ruiz Feliz",
     "vicepresidencia": "Servicio al Cliente",
     "area": "TECNICO BACK OFFICE TSR BACK OFFICE",
     "confirmacion": "Si",
     "posicion": "G",
     "estatura": "5-8",
     "equipo": "Draft",
     "ronda": "1",
     "pick": "0"
    },
    {
     "codigo": 27110,
     "nombre": "Ariel Jose de la Cruz",
     "vicepresidencia": "Servicio al Cliente",
     "area": "REPRESENTANTE JR DE RETENCION RETENTION INBOUND",
     "confirmacion": "Si",
     "posicion": "SG",
     "estatura": "6-5",
     "equipo": "Draft",
     "ronda": "1",
     "pick": "0"
    },
    {
     "codigo": 24029,
     "nombre": "Arismark Rivas Reyes",
     "vicepresidencia": "Servicio al Cliente",
     "area": "REPRESENTANTE SR SOLUCIONES TECNICAS B2B B2B OUTSOURCING",
     "confirmacion": "Si",
     "posicion": "F",
     "estatura": "5-10",
     "equipo": "Draft",
     "ronda": "1",
     "pick": "0"
    },
    {
     "codigo": 2454,
     "nombre": "Bergson Perez",
     "vicepresidencia": "Finanzas",
     "area": "INTERNAL CONTROL",
     "confirmacion": "No",
     "posicion": "G",
     "estatura": "5-6",
     "equipo": "Draft",
     "ronda": "2",
     "pick": "0"
    },
    {
     "codigo": 27165,
     "nombre": "Dalwin Rosario",
     "vicepresidencia": "Ventas",
     "area": "OWN SHOPS",
     "confirmacion": "Si",
     "posicion": "SG",
     "estatura": "5-11",
     "equipo": "Draft",
     "ronda": "2",
     "pick": "0"
    },
    {
     "codigo": 23299,
     "nombre": "David Estrella",
     "vicepresidencia": "TIS",
     "area": "INFRASTRUCTURE PLATFORMS",
     "confirmacion": "Si",
     "posicion": "G",
     "estatura": "5-8",
     "equipo": "Draft",
     "ronda": "2",
     "pick": "0"
    },
    {
     "codigo": 26929,
     "nombre": "Dennis Manuel  Hidalgo",
     "vicepresidencia": "Servicio al Cliente",
     "area": "REPRESENTANTE JR DE RETENCION  RETENTION INBOUND",
     "confirmacion": "Si",
     "posicion": "SG",
     "estatura": "5-10",
     "equipo": "Draft",
     "ronda": "2",
     "pick": "0"
    },
    {
     "codigo": 26805,
     "nombre": "Edwin Ventura",
     "vicepresidencia": "Ventas",
     "area": "OWN SHOPS",
     "confirmacion": "Si",
     "posicion": "G",
     "estatura": "5-8",
     "equipo": "Draft",
     "ronda": "3",
     "pick": "0"
    },
    {
     "codigo": 4453,
     "nombre": "Elias Hernandez",
     "vicepresidencia": "Finanzas",
     "area": "INTERNAL CONTROL",
     "confirmacion": "No",
     "posicion": "PF",
     "estatura": "6-3",
     "equipo": "Draft",
     "ronda": "3",
     "pick": "0"
    },
    {
     "codigo": 26010,
     "nombre": "Ernesto espejo",
     "vicepresidencia": "Ventas",
     "area": "OWN SHOPS",
     "confirmacion": "Si",
     "posicion": "PF\/C",
     "estatura": "6-4",
     "equipo": "Draft",
     "ronda": "3",
     "pick": "0"
    },
    {
     "codigo": 25146,
     "nombre": "Heberto Terrero",
     "vicepresidencia": "TIS",
     "area": "NETWORK",
     "confirmacion": "Si",
     "posicion": "G",
     "estatura": "5-7",
     "equipo": "Draft",
     "ronda": "3",
     "pick": "0"
    },
    {
     "codigo": 2031,
     "nombre": "Hector Berroa",
     "vicepresidencia": "TIS",
     "area": "INFRASTRUCTURE PLATFORMS",
     "confirmacion": "No",
     "posicion": "SG",
     "estatura": "5-8",
     "equipo": "Draft",
     "ronda": "4",
     "pick": "0"
    },
    {
     "codigo": 24991,
     "nombre": "Imanol Parra",
     "vicepresidencia": "Servicio al Cliente",
     "area": "COMMERCIAL QUALITY",
     "confirmacion": "Si",
     "posicion": "SG",
     "estatura": "5-9",
     "equipo": "Draft",
     "ronda": "4",
     "pick": "0"
    },
    {
     "codigo": 26278,
     "nombre": "Isaac Lopez",
     "vicepresidencia": "TIS",
     "area": "NETWORK",
     "confirmacion": "Si",
     "posicion": "SG \/F",
     "estatura": "5-10",
     "equipo": "Draft",
     "ronda": "4",
     "pick": "0"
    },
    {
     "codigo": 26578,
     "nombre": "Jefrey tejada",
     "vicepresidencia": "Ventas",
     "area": "TELESALES OUTBOUND",
     "confirmacion": "Si",
     "posicion": "F",
     "estatura": "6-2",
     "equipo": "Draft",
     "ronda": "4",
     "pick": "0"
    },
    {
     "codigo": 24161,
     "nombre": "Jheam Melenciano Perez",
     "vicepresidencia": "Servicio al Cliente",
     "area": "COMMERCIAL QUALITY",
     "confirmacion": "Si",
     "posicion": "G",
     "estatura": "5-7",
     "equipo": "Draft",
     "ronda": "5",
     "pick": "0"
    },
    {
     "codigo": 26609,
     "nombre": "Joaquin Alejandro Rodriguez Carvajal",
     "vicepresidencia": "TIS",
     "area": "INGENIERO JR DE REDES  FIXED ACCESS",
     "confirmacion": "Si",
     "posicion": "PF",
     "estatura": "6-2",
     "equipo": "Draft",
     "ronda": "5",
     "pick": "0"
    },
    {
     "codigo": 25002,
     "nombre": "Joe Jimenez",
     "vicepresidencia": "Finanzas",
     "area": "BILLING, CREDIT & COLLECTION",
     "confirmacion": "Si",
     "posicion": "PF",
     "estatura": "6-0",
     "equipo": "Draft",
     "ronda": "5",
     "pick": "0"
    },
    {
     "codigo": 23185,
     "nombre": "Joel rivas",
     "vicepresidencia": "Ventas",
     "area": "OWN SHOPS",
     "confirmacion": "Si",
     "posicion": "G",
     "estatura": "5-11",
     "equipo": "Draft",
     "ronda": "5",
     "pick": "0"
    },
    {
     "codigo": 23267,
     "nombre": "Johan Gil",
     "vicepresidencia": "Servicio al Cliente",
     "area": "CUSTOMER OPERATIONS",
     "confirmacion": "Si",
     "posicion": "PF",
     "estatura": "6-0",
     "equipo": "Draft",
     "ronda": "6",
     "pick": "0"
    },
    {
     "codigo": 24987,
     "nombre": "Johan Luis Sanchez",
     "vicepresidencia": "Servicio al Cliente",
     "area": "B2C TECHNICAL SOLUTIONS",
     "confirmacion": "Si",
     "posicion": "SG",
     "estatura": "5-11",
     "equipo": "Draft",
     "ronda": "6",
     "pick": "0"
    },
    {
     "codigo": 24949,
     "nombre": "Jorge Ramirez",
     "vicepresidencia": "Finanzas",
     "area": "BILLING, CREDIT & COLLECTION",
     "confirmacion": "Si",
     "posicion": "F",
     "estatura": "5-8",
     "equipo": "Draft",
     "ronda": "6",
     "pick": "0"
    },
    {
     "codigo": 25612,
     "nombre": "Jose Lantigua",
     "vicepresidencia": "Ventas",
     "area": "B2B SALES",
     "confirmacion": "Si",
     "posicion": "C",
     "estatura": "6-3",
     "equipo": "Draft",
     "ronda": "6",
     "pick": "0"
    },
    {
     "codigo": 25994,
     "nombre": "Jose Miguel Garcia",
     "vicepresidencia": "TIS",
     "area": "NETWORK",
     "confirmacion": "Si",
     "posicion": "F",
     "estatura": "5-9",
     "equipo": "Draft",
     "ronda": "7",
     "pick": "0"
    },
    {
     "codigo": 23485,
     "nombre": "Juan Marte",
     "vicepresidencia": "Mercadeo",
     "area": "MARKETING SEGMENTS",
     "confirmacion": "Si",
     "posicion": "C",
     "estatura": "6-4",
     "equipo": "Draft",
     "ronda": "7",
     "pick": "0"
    },
    {
     "codigo": 19580,
     "nombre": "Julio Frias",
     "vicepresidencia": "Finanzas",
     "area": "INTERNAL CONTROL",
     "confirmacion": "Si",
     "posicion": "F",
     "estatura": "6-0",
     "equipo": "Draft",
     "ronda": "7",
     "pick": "0"
    },
    {
     "codigo": 23179,
     "nombre": "Kilvio Yeniel Ramírez Gómez",
     "vicepresidencia": "Ventas",
     "area": "OWN SHOPS",
     "confirmacion": "Si",
     "posicion": "SG",
     "estatura": "5-8",
     "equipo": "Draft",
     "ronda": "7",
     "pick": "0"
    },
    {
     "codigo": 24978,
     "nombre": "Luis Pozo",
     "vicepresidencia": "Servicio al Cliente",
     "area": "CUSTOMER EXPERIENCE",
     "confirmacion": "Si",
     "posicion": "F",
     "estatura": "6-0",
     "equipo": "Draft",
     "ronda": "8",
     "pick": "0"
    },
    {
     "codigo": 26481,
     "nombre": "Manuel de Jesus de los Santos",
     "vicepresidencia": "Ventas",
     "area": "OWN SHOPS",
     "confirmacion": "Si",
     "posicion": "G",
     "estatura": "5-8",
     "equipo": "Draft",
     "ronda": "8",
     "pick": "0"
    },
    {
     "codigo": 24270,
     "nombre": "Miguel Zaro",
     "vicepresidencia": "Servicio al Cliente",
     "area": "B2C TECHNICAL SOLUTIONS",
     "confirmacion": "Si",
     "posicion": "G",
     "estatura": "5-7",
     "equipo": "Draft",
     "ronda": "8",
     "pick": "0"
    },
    {
     "codigo": 25639,
     "nombre": "Moises Rojas",
     "vicepresidencia": "TIS",
     "area": "NETWORK",
     "confirmacion": "Si",
     "posicion": "SG",
     "estatura": "5-5",
     "equipo": "Draft",
     "ronda": "8",
     "pick": "0"
    },
    {
     "codigo": 26131,
     "nombre": "Rafael Brache",
     "vicepresidencia": "TIS",
     "area": "INFORMATION SYSTEMS",
     "confirmacion": "Si",
     "posicion": "SG",
     "estatura": "5-9",
     "equipo": "Draft",
     "ronda": "9",
     "pick": "0"
    },
    {
     "codigo": 23091,
     "nombre": "Rafael Genao",
     "vicepresidencia": "Ventas",
     "area": "B2B SALES",
     "confirmacion": "Si",
     "posicion": "PF",
     "estatura": "6",
     "equipo": "Draft",
     "ronda": "9",
     "pick": "0"
    },
    {
     "codigo": 23283,
     "nombre": "Rainer Aponte",
     "vicepresidencia": "TIS",
     "area": "NETWORK",
     "confirmacion": "Si",
     "posicion": "F",
     "estatura": "5-9",
     "equipo": "Draft",
     "ronda": "9",
     "pick": "0"
    },
    {
     "codigo": 24507,
     "nombre": "Raul Nuñez",
     "vicepresidencia": "Servicio al Cliente",
     "area": "B2C TECHNICAL SOLUTIONS",
     "confirmacion": "Si",
     "posicion": "G",
     "estatura": "5-10",
     "equipo": "Draft",
     "ronda": "9",
     "pick": "0"
    },
    {
     "codigo": 25911,
     "nombre": "Rendy Figuereo",
     "vicepresidencia": "Servicio al Cliente",
     "area": "RETENTION",
     "confirmacion": "Si",
     "posicion": "F",
     "estatura": "5-11",
     "equipo": "Draft",
     "ronda": "10",
     "pick": "0"
    },
    {
     "codigo": 25683,
     "nombre": "Reymir Vásquez Álvarez",
     "vicepresidencia": "Ventas",
     "area": "OWN SHOPS",
     "confirmacion": "Si",
     "posicion": "C",
     "estatura": "6-3",
     "equipo": "Draft",
     "ronda": "10",
     "pick": "0"
    },
    {
     "codigo": 23978,
     "nombre": "Samuel Torres",
     "vicepresidencia": "TIS",
     "area": "CORE NETWORK",
     "confirmacion": "Si",
     "posicion": "G",
     "estatura": "5-9",
     "equipo": "Draft",
     "ronda": "10",
     "pick": "0"
    },
    {
     "codigo": 2146,
     "nombre": "Socrates Diaz",
     "vicepresidencia": "Ventas",
     "area": "QUALITY SALES",
     "confirmacion": "Si",
     "posicion": "C",
     "estatura": "6-4",
     "equipo": "Draft",
     "ronda": "10",
     "pick": "0"
    },
    {
     "codigo": 23544,
     "nombre": "Victor Consuegra",
     "vicepresidencia": "Finanzas",
     "area": "ACCOUNTING",
     "confirmacion": "Si",
     "posicion": "F",
     "estatura": "5-9",
     "equipo": "Draft",
     "ronda": "11",
     "pick": "0"
    },
    {
     "codigo": 25850,
     "nombre": "Widhinson Escalona",
     "vicepresidencia": "Ventas",
     "area": "OWN SHOPS",
     "confirmacion": "Si",
     "posicion": "SG",
     "estatura": "5-11",
     "equipo": "Draft",
     "ronda": "11",
     "pick": "0"
    },
    {
     "codigo": 25368,
     "nombre": "Wilson Veras",
     "vicepresidencia": "Finanzas",
     "area": "BILLING, CREDIT & COLLECTION",
     "confirmacion": "Si",
     "posicion": "G",
     "estatura": "5-7",
     "equipo": "Draft",
     "ronda": "11",
     "pick": "0"
    },
    {
     "codigo": 4111,
     "nombre": "Winkler Rubio",
     "vicepresidencia": "Finanzas",
     "area": "INTERNAL CONTROL",
     "confirmacion": "Si",
     "posicion": "PF",
     "estatura": "5-11",
     "equipo": "Draft",
     "ronda": "11",
     "pick": "0"
    }
   ]
}